# Simple script to shamelessly rip off regex lexers in pygments and convert
# them to C++ format.

from pygments.lexers import CppLexer
import os
import pprint
import pygments.token


def fix_regex(string):
  return string.encode('string_escape').replace('"', '\\"')


def fix_action(action):
  action = str(action)
  action = action.replace('Token.', 'Lexer::')
  action = action.replace('.', '')
  return action


def main():
  print '// THIS FILE AUTOGENERATED BY %s. DO NOT EDIT.' % (
      os.path.basename(__file__))
  print
  print '#include "lexer.h"'
  print
  print 'Lexer* MakeCppLexer() {'
  print '  Lexer* lexer = new Lexer("C++");'
  print

  print '  // States'
  for state, regexes in sorted(CppLexer.tokens.iteritems()):
    print '  LexerState* %s = lexer->AddState("%s");' % (state, state)
  print

  for state, regexes in sorted(CppLexer.tokens.iteritems()):
    print '  // Transitions for %s' % state
    for item in regexes:
      assert len(item) in (2, 3)
      if len(item) == 2:
        regex, action = item
        if not isinstance(action, pygments.token._TokenType):
          print '  // TODO(%s)' % type(action),
        print '  %s->Add("%s", %s);' % (
            state, fix_regex(regex), fix_action(action))
      elif len(item) == 3:
        regex, action, new_state = item
        if new_state == '#pop':
          new_state = 'Lexer::Pop'
        elif new_state == '#push':
          new_state = 'Lexer::Push'
        if not isinstance(action, pygments.token._TokenType):
          print '  // TODO(%s)' % type(action),
        print '  %s->AddWithTransition("%s", %s, %s);' % (
            state, fix_regex(regex), fix_action(action), new_state)
    print

  print '  return lexer;'
  print '}'

if __name__ == '__main__':
  main()
